development:
  adapter: postgresql
  encoding: unicode
  database: schatter_development
  pool: 5
  username: schatter
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: schatter_test
  pool: 5
  username: schatter
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: schatter_production
  pool: 5
  username: schatter
  password:
